on:
  pull_request:

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
      - name: Check linting
        run: uv run ruff check
      - name: Check format
        run: uv run ruff format --check
      - name: Check types
        run: uv run ty check
  ci-pass:
    name: Check CI Pass
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Print success message
        run: echo "CI checks passed successfully!"
